---
# Copyright 2018, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Update libvirt's cpu_map.xml to include custom definition ('Haswell-Plus') for nested virt (vmx)
  hosts: compute_hosts
  tasks:
    - name: Copy custom cpu_map.xml
      copy:
        src: "files/cpu_map.xml"
        dest: "/usr/share/libvirt/cpu_map.xml"
        owner: root
        group: root
        mode: 0644
      tags: cpu-map
    - name: Restart the libvirt-bin service
      service:
        name: libvirt-bin
        state: restarted

- name: Apply nova libvirt driver.py patch file
  hosts: compute_hosts
  tasks:
    - name: Apply nova libvirt driver.py patch file
      patch:
        src: "files/driver.py.patch"
        dest: "/openstack/venvs/nova-{{openstack_release}}/lib/python2.7/site-packages/nova/virt/libvirt/driver.py"
        backup: yes
      tags: nova-libvirt-driver
    - name: Restart the nova-compute service
      service:
        name: nova-compute
        state: restarted

- name: Copy Aggregate Domain Isolation Filter to Nova Scheduler Containers
  hosts: nova_scheduler
  tasks:
     - name: Copy aggregate domain filter to scheduler containers
       copy:
          src: "../files/aggregate_domain_isolation.py"
          dest: "/openstack/venvs/nova-{{openstack_release}}/lib/python2.7/site-packages/nova/scheduler/filters/"
          owner: root
          group: root
          mode: "0644"
       tags: nova-scheduler-filter
     - name: Restart the nova scheduler services
       service:
         name: "nova-scheduler"
         state: restarted
  vars:
    openstack_release: "r14.10.0"

-name: Pin libvirt/qemu packages
  hosts: compute_hosts
  tasks:
    - name: Copy apt preferences file
      copy:
        src: "files/libvirt_qemu.pref"
        dest: "/etc/apt/preferences.d/libvirt_qemu.pref"
        owner: root
        group: root
        mode: 0644
      tags: pin-packages

