---
# Copyright 2018, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Update libvirt's cpu_map.xml to include custom definition ('Haswell-Plus') for nested virt (vmx)
  hosts: compute_hosts
  tasks:
    - name: Copy custom cpu_map.xml
      dest:
        src: "files/cpu_map.xml"
        dest: "/usr/share/libvirt/cpu_map.xml"
        owner: root
        group: root
        mode: 0644
    - name: Restart the libvirt-bin service
      service:
        name: libvirt-bin
        state: restarted
